#!/usr/bin/env python3
"""The war agent's decision as a 0/1 knapsack across the front line.

Run: python3 writeup/figs/knapsack_war/generate.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from _diagram_lib import (  # noqa: E402
    TikzWriter, tikzpicture_preamble, tikzpicture_footer, build_pdf,
)

NAME = HERE.name
R = "7pt"

OURS = [("120", 0.6), ("80", 2.2), ("50", 3.8)]
TARGETS = [  # name, x, price, value, chosen
    ("empty",      0.3, 30, 0.5, False),
    ("factory",    1.7, 90, 1,   True),
    ("powerplant", 3.1, 150, 2,  True),
    ("capital",    4.5, 300, 5,  False),
]
ARROWS = [(0.6, 1.7), (2.2, 1.7), (2.2, 3.1), (3.8, 3.1)]


def emit() -> Path:
    w = TikzWriter()
    w.line(tikzpicture_preamble(
        cv_unit="1.25cm",
        note=f"Auto-generated by writeup/figs/{NAME}/generate.py.",
    ))

    # attack arrows first (under the nodes)
    for sx, tx in ARROWS:
        w.line(f"    \\draw[consign] ({sx},0.18) -- ({tx},1.32);")

    # our frontier
    for label, x in OURS:
        w.filled_circle(np.array((x, 0)), R, "ours")
        w.node(np.array((x, 0)), rf"\scriptsize\textbf{{{label}}}",
               "anchor=center")
    w.node(np.array((2.2, -0.55)),
           r"\small our frontier: budget $=250$ troops", "anchor=center")

    # front line
    w.line("    \\draw[frontline] (-0.5,0.75) -- (5.4,0.75);")
    w.node(np.array((5.35, 0.9)), r"\footnotesize\textcolor{black!55}{front line}",
           "anchor=east")

    # enemy targets
    for name, x, price, value, chosen in TARGETS:
        w.filled_circle(np.array((x, 1.5)), R, "enemy")
        if chosen:
            w.circle(np.array((x, 1.5)), "11pt", "chosen")
        w.node(np.array((x, 1.95)), rf"\footnotesize\textbf{{{name}}}",
               "anchor=south")
        w.node(np.array((x, 2.32)),
               rf"\footnotesize $p{{=}}{price}$, $v{{=}}{value}$",
               "anchor=south")

    w.node(np.array((2.2, 3.15)),
           r"\small chosen basket: price $240 \leq 250$, value $3$",
           "anchor=center")

    w.line(tikzpicture_footer())
    out = HERE / f"{NAME}.tex"
    out.write_text(w.render())
    return out


if __name__ == "__main__":
    emit()
    build_pdf(NAME, HERE, cv_unit="1.25cm")
