#!/usr/bin/env python3
"""The war agent's knapsack, on a game-like mesh patch.

A ragged front runs through a geometric-graph patch: our side (blue, troop
counts on the frontier), enemy side (red). The four enemy nodes reachable
across the front get price/value tags in a margin column with leader lines;
the chosen basket is ringed.

Run: python3 writeup/figs/knapsack_war/generate.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from _diagram_lib import (  # noqa: E402
    TikzWriter, tikzpicture_preamble, tikzpicture_footer, build_pdf,
    poisson_patch,
)

NAME = HERE.name
R = "4.6pt"
SEED = 7


def emit() -> Path:
    P, edges = poisson_patch(SEED, n=24)
    mid_x = np.median(P[:, 0])
    ours = {i for i in range(len(P)) if P[i, 0] < mid_x}

    cut = [(i, j) for i, j in edges if (i in ours) != (j in ours)]
    our_front = sorted({i if i in ours else j for i, j in cut},
                       key=lambda i: -P[i, 1])
    enemy_front = sorted({j if i in ours else i for i, j in cut},
                         key=lambda i: -P[i, 1])

    budgets = ["120", "80", "50"]
    front_troops = {i: budgets[k] for k, i in enumerate(our_front[:3])}
    tags = [("factory", 90, 1, True), ("powerplant", 150, 2, True),
            ("capital", 300, 5, False), ("empty", 30, 0.5, False)]
    targets = enemy_front[:4]
    target_info = dict(zip(targets, tags))

    w = TikzWriter()
    w.line(tikzpicture_preamble(
        cv_unit="1.2cm",
        note=f"Auto-generated by writeup/figs/{NAME}/generate.py.",
    ))

    for i, j in edges:
        style = ("frontline" if (i in ours) != (j in ours)
                 else "draw=black!35, line width=0.4pt")
        w.edge(P[i], P[j], style)

    # margin label column with leader lines
    label_x = P[:, 0].max() + 1.15
    label_ys = np.linspace(P[:, 1].max(), P[:, 1].min(), len(targets))
    for (tgt, (name, price, value, chosen)), ly in zip(
            sorted(target_info.items(), key=lambda kv: -P[kv[0], 1]),
            label_ys):
        w.line(f"    \\draw[draw=black!40, line width=0.35pt] "
               f"({P[tgt][0]:.4f},{P[tgt][1]:.4f}) -- "
               f"({label_x - 0.12:.4f},{ly:.4f});")
        star = r"\ \textcolor{green!45!black}{$\checkmark$}" if chosen else ""
        w.node(np.array((label_x, ly)),
               rf"\scriptsize {name}: $p{{=}}{price}$, $v{{=}}{value}${star}",
               "anchor=west, fill=white, inner sep=1.5pt")

    # attack arrows into the chosen basket
    chosen_nodes = [t for t in targets if target_info[t][3]]
    for tgt in chosen_nodes:
        srcs = sorted(front_troops,
                      key=lambda i: np.linalg.norm(P[i] - P[tgt]))[:2]
        for sidx in srcs:
            a, b = P[sidx], P[tgt]
            d = (b - a) / np.linalg.norm(b - a)
            w.line(f"    \\draw[consign] "
                   f"({a[0] + 0.18*d[0]:.4f},{a[1] + 0.18*d[1]:.4f}) -- "
                   f"({b[0] - 0.2*d[0]:.4f},{b[1] - 0.2*d[1]:.4f});")

    for i in range(len(P)):
        if i in ours:
            w.filled_circle(P[i], R, "ours")
            if i in front_troops:
                w.node(P[i], rf"\tiny\textbf{{{front_troops[i]}}}",
                       "anchor=center")
        else:
            w.filled_circle(P[i], R, "enemy")
            if i in target_info and target_info[i][3]:
                w.circle(P[i], "8pt", "chosen")

    cx = (P[:, 0].max() + label_x) / 2 - 1.4
    w.node(np.array((cx, -0.5)),
           r"\small frontier budget $= 250$ troops \quad$\Rightarrow$\quad "
           r"chosen basket: price $240 \leq 250$, value $3$",
           "anchor=center")

    w.line(tikzpicture_footer())
    out = HERE / f"{NAME}.tex"
    out.write_text(w.render())
    return out


if __name__ == "__main__":
    emit()
    build_pdf(NAME, HERE, cv_unit="1.2cm")
