#!/usr/bin/env python3
"""Two views of one transport problem, on a game-like mesh patch.

Same patch, same instance (one surplus node, two deficit nodes) in both
panels. The pressure panel colors nodes by the actual solution of the graph
Poisson equation (what gradient transport computes each tick) with downhill
arrows on the steepest edges; the manifest panel shows OT's explicit
consignments routed along shortest paths.

Run: python3 writeup/figs/transport_views/generate.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from _diagram_lib import (  # noqa: E402
    TikzWriter, Palette, fmt, tikzpicture_preamble, tikzpicture_footer,
    build_pdf, poisson_patch, shortest_path, graph_poisson_potential,
)

NAME = HERE.name
R = "3.6pt"
SEED = 21


def emit() -> Path:
    P, edges = poisson_patch(SEED)
    # surplus: leftmost node; deficits: two right-side nodes far apart.
    src = int(np.argmin(P[:, 0]))
    right = np.argsort(-P[:, 0])[:6]
    dst1 = int(right[0])
    dst2 = int(max(right[1:], key=lambda i: np.linalg.norm(P[i] - P[dst1])))

    b = np.zeros(len(P))
    b[src], b[dst1], b[dst2] = 100, -60, -40
    phi = graph_poisson_potential(P, edges, b)
    phi = phi / phi.max()

    pal = Palette("viridis", alpha=0.6)
    w = TikzWriter()
    w.line(tikzpicture_preamble(
        cv_unit="1.05cm",
        note=f"Auto-generated by writeup/figs/{NAME}/generate.py.",
    ))

    def tags(w):
        for node_i, txt in ((src, "$+100$"), (dst1, "$-60$"), (dst2, "$-40$")):
            w.node(P[node_i] + np.array((0, 0.28)),
                   rf"\footnotesize\textbf{{{txt}}}", "anchor=south")

    # (a) pressure view ---------------------------------------------------
    w.begin_scope("shift={(0,0)}")
    drops = sorted(edges, key=lambda e: -abs(phi[e[0]] - phi[e[1]]))
    steep = set(map(tuple, drops[:14]))
    for i, j in edges:
        w.edge(P[i], P[j], "draw=black!30, line width=0.4pt")
    for i, j in steep:
        a, bnode = (i, j) if phi[i] > phi[j] else (j, i)
        pa, pb = P[a], P[bnode]
        m, d = (pa + pb) / 2, pb - pa
        d = d / np.linalg.norm(d)
        w.line(f"    \\draw[-{{Stealth[length=3.5pt]}}, draw=black!80, "
               f"line width=0.65pt] "
               f"({fmt(m[0]-0.16*d[0])},{fmt(m[1]-0.16*d[1])}) -- "
               f"({fmt(m[0]+0.16*d[0])},{fmt(m[1]+0.16*d[1])});")
    for i in range(len(P)):
        w.filled_circle(P[i], R, pal.fill_spec(phi[i])
                        + ", draw=black, line width=0.4pt")
    tags(w)
    w.node(np.array((2.6, -0.55)),
           r"\small\textbf{(a)} pressure: solve $L\phi=b$, roll downhill",
           "anchor=center")
    w.end_scope()

    # (b) manifest view ---------------------------------------------------
    w.begin_scope("shift={(7.0,0)}")
    path1 = shortest_path(P, edges, src, dst1)
    path2 = shortest_path(P, edges, src, dst2)
    on1 = {tuple(sorted(e)) for e in zip(path1, path1[1:])}
    on2 = {tuple(sorted(e)) for e in zip(path2, path2[1:])}
    for i, j in edges:
        key = tuple(sorted((i, j)))
        if key in on1 or key in on2:
            continue
        w.edge(P[i], P[j], "draw=black!25, line width=0.4pt")
    for pth, style in ((path1, "draw=green!55!black, line width=1.3pt"),
                       (path2, "draw=green!55!black, line width=1.3pt, "
                               "dash pattern=on 3pt off 1.6pt")):
        for a, bnode in zip(pth, pth[1:]):
            w.edge(P[a], P[bnode], style)
    for i in range(len(P)):
        if i == src:
            spec = "ours"
        elif i in (dst1, dst2):
            spec = "fill=green!45!black!35, draw=black, line width=0.4pt"
        else:
            spec = "fill=black!10, draw=black!45, line width=0.4pt"
        w.filled_circle(P[i], R, spec)
    tags(w)
    m1 = P[path1[len(path1) // 2]]
    m2 = P[path2[len(path2) // 2]]
    w.node(m1 + np.array((0, 0.3)),
           r"\footnotesize\textcolor{green!45!black}{send 60}",
           "anchor=south")
    w.node(m2 + np.array((0, -0.3)),
           r"\footnotesize\textcolor{green!45!black}{send 40}",
           "anchor=north")
    w.node(np.array((2.6, -0.55)),
           r"\small\textbf{(b)} manifest: consignments, cheapest routes",
           "anchor=center")
    w.end_scope()

    w.line(tikzpicture_footer())
    out = HERE / f"{NAME}.tex"
    out.write_text(w.render())
    return out


if __name__ == "__main__":
    emit()
    build_pdf(NAME, HERE, cv_unit="1.05cm")
