#!/usr/bin/env python3
"""Two views of one transport problem: pressure field vs shipping manifest.

Run: python3 writeup/figs/transport_views/generate.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from _diagram_lib import (  # noqa: E402
    TikzWriter, Palette, fmt, tikzpicture_preamble, tikzpicture_footer,
    build_pdf,
)

NAME = HERE.name
R = "6pt"

POS = {"A": (0, 0), "B": (1.1, 0), "C": (2.2, 0),
       "D": (3.3, 0.85), "E": (3.3, -0.85), "F": (4.4, -0.85)}
EDGES = [("A", "B"), ("B", "C"), ("C", "D"), ("C", "E"), ("E", "F")]
PRESSURE = {"A": 1.0, "B": 0.78, "C": 0.55, "D": 0.3, "E": 0.3, "F": 0.05}
FLOWS = [("A", "B", 100), ("B", "C", 100), ("C", "D", 60),
         ("C", "E", 40), ("E", "F", 40)]
TAGS = {"A": "+100", "D": "-60", "F": "-40"}


def tag(w, name, dy=0.42):
    p = POS[name]
    body = TAGS[name].replace("-", "$-$").replace("+", "$+$")
    w.node(np.array((p[0], p[1] + dy)), rf"\small\textbf{{{body}}}",
           "anchor=south")


def node_label(w, name):
    p = POS[name]
    w.node(np.array(p), rf"\scriptsize\textbf{{{name}}}", "anchor=center")


def emit() -> Path:
    pal = Palette("viridis", alpha=0.6)
    w = TikzWriter()
    w.line(tikzpicture_preamble(
        cv_unit="1.15cm",
        note=f"Auto-generated by writeup/figs/{NAME}/generate.py.",
    ))

    # (a) pressure view
    w.begin_scope("shift={(0,0)}")
    for a, b in EDGES:
        w.edge(np.array(POS[a]), np.array(POS[b]), "gedge")
    for a, b, f in FLOWS:
        pa, pb = np.array(POS[a]), np.array(POS[b])
        m, d = (pa + pb) / 2, pb - pa
        d = d / np.linalg.norm(d)
        lw = 0.5 + f / 90
        w.line(f"    \\draw[-{{Stealth[length={fmt(3.5 + f/40)}pt]}}, "
               f"draw=black!80, line width={fmt(lw)}pt] "
               f"({fmt(m[0] - 0.22*d[0])},{fmt(m[1] - 0.22*d[1])}) -- "
               f"({fmt(m[0] + 0.22*d[0])},{fmt(m[1] + 0.22*d[1])});")
    for name, p in POS.items():
        w.filled_circle(np.array(p), R,
                        pal.fill_spec(PRESSURE[name]) +
                        ", draw=black, line width=0.5pt")
        w.node(np.array(p), rf"\scriptsize\textbf{{\textcolor{{white}}{{{name}}}}}"
               if PRESSURE[name] < 0.45 else rf"\scriptsize\textbf{{{name}}}",
               "anchor=center")
    for t in TAGS:
        tag(w, t)
    w.node(np.array((2.2, -2.2)),
           r"\small\textbf{(a)} pressure view: troops roll downhill",
           "anchor=center")
    w.end_scope()

    # (b) manifest view
    w.begin_scope("shift={(6.2,0)}")
    for a, b in EDGES:
        w.edge(np.array(POS[a]), np.array(POS[b]), "gedge")
    for name, p in POS.items():
        style = "ours" if name == "A" else ("chosenfill" if name in ("D", "F")
                                            else "neutral")
        spec = {"ours": "ours", "chosenfill":
                "fill=green!45!black!35, draw=black, line width=0.5pt",
                "neutral": "neutral"}[style]
        w.filled_circle(np.array(p), R, spec)
        node_label(w, name)
    for t in TAGS:
        tag(w, t)
    w.line("    \\draw[consign] (0,0.28) to[bend left=32] "
           "node[midway, above, font=\\footnotesize] {send 60} (3.05,1.0);")
    w.line("    \\draw[consign] (0.05,-0.28) to[bend right=38] "
           "node[pos=0.32, below, font=\\footnotesize] {send 40} (4.3,-1.15);")
    w.node(np.array((2.2, -2.2)),
           r"\small\textbf{(b)} manifest view: explicit consignments",
           "anchor=center")
    w.end_scope()

    w.line(tikzpicture_footer())
    out = HERE / f"{NAME}.tex"
    out.write_text(w.render())
    return out


if __name__ == "__main__":
    emit()
    build_pdf(NAME, HERE, cv_unit="1.15cm")
