#!/usr/bin/env python3
"""Global vs local softmax on a game-like mesh patch.

Same patch and node scores (two hotspots, one slightly higher) in both
panels; arrows show where each node's troops are pulled. Global: everything
drains to the single best node on the map. Local (v8): pull decays with
distance, so each region feeds its own hotspot.

Run: python3 writeup/figs/softmax_views/generate.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from _diagram_lib import (  # noqa: E402
    TikzWriter, Palette, fmt, tikzpicture_preamble, tikzpicture_footer,
    build_pdf, poisson_patch,
)

NAME = HERE.name
R = "3.6pt"
SEED = 33


def emit() -> Path:
    P, edges = poisson_patch(SEED)
    # hotspots: two far-apart nodes
    h1 = int(np.argmin(P[:, 0] - 0.4 * P[:, 1]))
    h2 = int(np.argmax(P[:, 0] + 0.4 * P[:, 1]))
    scores = (1.00 * np.exp(-0.55 * np.linalg.norm(P - P[h1], axis=1) ** 2)
              + 0.85 * np.exp(-0.55 * np.linalg.norm(P - P[h2], axis=1) ** 2))
    scores /= scores.max()

    pal = Palette("viridis", alpha=0.65)
    w = TikzWriter()
    w.line(tikzpicture_preamble(
        cv_unit="1.0cm",
        note=f"Auto-generated by writeup/figs/{NAME}/generate.py.",
    ))

    for panel, local in ((0, False), (1, True)):
        xoff = panel * 6.6
        w.begin_scope(f"shift={{({fmt(xoff)},0)}}")
        for i, j in edges:
            w.edge(P[i], P[j], "draw=black!22, line width=0.35pt")
        for i in range(len(P)):
            if i in (h1, h2):
                continue
            d1 = np.linalg.norm(P[i] - P[h1])
            d2 = np.linalg.norm(P[i] - P[h2])
            target = h1 if (not local or d1 <= d2) else h2
            a, b = P[i], P[target]
            d = (b - a) / np.linalg.norm(b - a)
            w.line(f"    \\draw[-{{Stealth[length=3pt]}}, draw=black!55, "
                   f"line width=0.5pt, opacity=0.75] "
                   f"({fmt(a[0]+0.14*d[0])},{fmt(a[1]+0.14*d[1])}) -- "
                   f"({fmt(b[0]-0.22*d[0])},{fmt(b[1]-0.22*d[1])});")
        for i in range(len(P)):
            w.filled_circle(P[i], "4.4pt" if i in (h1, h2) else R,
                            pal.fill_spec(scores[i])
                            + ", draw=black, line width=0.4pt")
        w.node(P[h1] + np.array((0, -0.3)), r"\footnotesize score 1.0",
               "anchor=north")
        w.node(P[h2] + np.array((0, -0.3)), r"\footnotesize score 0.9",
               "anchor=north")
        title = (r"\small\textbf{(a)} global softmax: one auction"
                 if not local else
                 r"\small\textbf{(b)} local softmax (v8): many auctions")
        w.node(np.array((2.6, 3.75)), title, "anchor=center")
        w.end_scope()

    w.line(tikzpicture_footer())
    out = HERE / f"{NAME}.tex"
    out.write_text(w.render())
    return out


if __name__ == "__main__":
    emit()
    build_pdf(NAME, HERE, cv_unit="1.0cm")
