#!/usr/bin/env python3
"""Global vs local softmax: one auction or many.

Run: python3 writeup/figs/softmax_views/generate.py
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from _diagram_lib import (  # noqa: E402
    TikzWriter, Palette, fmt, tikzpicture_preamble, tikzpicture_footer,
    build_pdf,
)

NAME = HERE.name
N = 13
PEAKS = (3, 10)


def score(i: int) -> float:
    return (1.0 * math.exp(-0.5 * (i - PEAKS[0]) ** 2)
            + 0.85 * math.exp(-0.5 * (i - PEAKS[1]) ** 2))


def emit() -> Path:
    pal = Palette("viridis", alpha=0.65)
    xs = [i * 0.62 for i in range(N)]
    scores = [score(i) for i in range(N)]
    smax = max(scores)

    w = TikzWriter()
    w.line(tikzpicture_preamble(
        cv_unit="1.0cm",
        note=f"Auto-generated by writeup/figs/{NAME}/generate.py.",
    ))

    for panel, local in ((0, False), (1, True)):
        xoff = panel * 9.2
        w.begin_scope(f"shift={{({fmt(xoff)},0)}}")
        for i, x in enumerate(xs):
            if i in PEAKS:
                continue
            target = PEAKS[0] if (not local or
                                  abs(i - PEAKS[0]) <= abs(i - PEAKS[1])) \
                else PEAKS[1]
            bend = "left" if xs[target] > x else "right"
            amt = 20 + min(58, 9 * abs(target - i))
            w.line(f"    \\draw[flow, opacity=0.65] ({fmt(x)},0.14) "
                   f"to[bend {bend}={amt}] ({fmt(xs[target])},0.2);")
        for i, x in enumerate(xs):
            w.filled_circle(np.array((x, 0)), "3.4pt",
                            pal.fill_spec(scores[i] / smax)
                            + ", draw=black, line width=0.4pt")
        for i, lbl in ((PEAKS[0], "score 1.0"), (PEAKS[1], "score 0.9")):
            w.node(np.array((xs[i], -0.32)), rf"\footnotesize {lbl}",
                   "anchor=north")
        title = (r"\small\textbf{(a)} global softmax: one auction"
                 if not local else
                 r"\small\textbf{(b)} local softmax (v8): many auctions")
        w.node(np.array((xs[-1] / 2, 2.05)), title, "anchor=center")
        w.end_scope()

    w.line(tikzpicture_footer())
    out = HERE / f"{NAME}.tex"
    out.write_text(w.render())
    return out


if __name__ == "__main__":
    emit()
    build_pdf(NAME, HERE, cv_unit="1.0cm")
