#!/usr/bin/env python3
"""Building as a frustrated Ising problem, on a game-like mesh patch.

(a) the payoff motif in situ: one powerplant and its factory neighbors,
    highlighted inside a real geometric-graph neighborhood;
(b) an annealed two-coloring of the same patch: alternation succeeds where
    the mesh is locally even, and every triangle forces a frustrated edge
    --- on these graphs frustration is the generic condition, not an edge
    case.

Run: python3 writeup/figs/economy_ising/generate.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from _diagram_lib import (  # noqa: E402
    TikzWriter, tikzpicture_preamble, tikzpicture_footer, build_pdf,
    poisson_patch, neighbors, anneal_two_coloring,
)

NAME = HERE.name
R = "4pt"
SEED = 12


def emit() -> Path:
    P, edges = poisson_patch(SEED)
    adj = neighbors(len(P), edges)
    s = anneal_two_coloring(P, edges, seed=3)

    # motif: the node whose neighborhood has the most opposite-colored
    # neighbors under the annealed layout, recolored as the powerplant.
    hub = max(range(len(P)), key=lambda i: len(adj[i]))

    w = TikzWriter()
    w.line(tikzpicture_preamble(
        cv_unit="1.05cm",
        note=f"Auto-generated by writeup/figs/{NAME}/generate.py.",
    ))

    # (a) payoff motif in situ ------------------------------------------
    w.begin_scope("shift={(0,0)}")
    ring = set(adj[hub])
    for i, j in edges:
        in_motif = (hub in (i, j)) and (i in ring or j in ring or hub in (i, j))
        style = "gedge" if in_motif else "draw=black!25, line width=0.4pt"
        if hub in (i, j):
            style = "draw=black!80, line width=0.7pt"
        w.edge(P[i], P[j], style)
    for i in range(len(P)):
        if i == hub:
            w.filled_circle(P[i], R, "pplant")
            w.node(P[i], r"\tiny\textbf{P}", "anchor=center")
        elif i in ring:
            w.filled_circle(P[i], R, "factory")
            w.node(P[i], r"\tiny\textbf{F}", "anchor=center")
            v = P[i] - P[hub]
            v = v / np.linalg.norm(v)
            w.node(P[i] + 0.38 * v, r"\scriptsize$+2$", "anchor=center")
        else:
            w.filled_circle(P[i], R, "fill=black!10, draw=black!45, "
                                     "line width=0.4pt")
    w.node(np.array((2.6, 3.75)),
           r"\small\textbf{(a)} the payoff motif, in situ", "anchor=center")
    w.end_scope()

    # (b) annealed layout on the same patch -----------------------------
    w.begin_scope("shift={(6.4,0)}")
    n_frustrated = 0
    for i, j in edges:
        if s[i] == s[j]:
            w.edge(P[i], P[j], "frustrated")
            n_frustrated += 1
        else:
            w.edge(P[i], P[j], "gedge")
    for i in range(len(P)):
        kind = "pplant" if s[i] > 0 else "factory"
        w.filled_circle(P[i], R, kind)
        w.node(P[i], rf"\tiny\textbf{{{'P' if s[i] > 0 else 'F'}}}",
               "anchor=center")
    w.node(np.array((2.6, 3.75)),
           r"\small\textbf{(b)} best layout: every triangle"
           r" leaves a \textcolor{red!75!black}{frustrated} edge",
           "anchor=center")
    w.end_scope()

    w.line(tikzpicture_footer())
    out = HERE / f"{NAME}.tex"
    out.write_text(w.render())
    print(f"  frustrated edges in annealed layout: {n_frustrated}/{len(edges)}")
    return out


if __name__ == "__main__":
    emit()
    build_pdf(NAME, HERE, cv_unit="1.05cm")
