#!/usr/bin/env python3
"""Building as a frustrated Ising problem: payoff motif, even cycle, odd cycle.

Run: python3 writeup/figs/economy_ising/generate.py
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from _diagram_lib import (  # noqa: E402
    TikzWriter, tikzpicture_preamble, tikzpicture_footer, build_pdf,
)

NAME = HERE.name
R = "5pt"


def game_node(w, p, kind, label):
    w.filled_circle(np.array(p), R, kind)
    w.node(np.array(p), rf"\scriptsize\textbf{{{label}}}", "anchor=center")


def panel_title(w, x, y, letter, text):
    w.node(np.array([x, y]), rf"\small\textbf{{({letter})}} {text}",
           "anchor=center")


def emit() -> Path:
    w = TikzWriter()
    w.line(tikzpicture_preamble(
        cv_unit="1.05cm",
        note=f"Auto-generated by writeup/figs/{NAME}/generate.py.",
    ))

    # (a) payoff motif: powerplant hub, factory ring
    w.begin_scope("shift={(0,0)}")
    ring = [(math.cos(a), math.sin(a))
            for a in [math.pi / 2 + i * 2 * math.pi / 5 for i in range(5)]]
    for p in ring:
        w.edge(np.array((0, 0)), np.array(p), "gedge")
    for p in ring:
        game_node(w, p, "factory", "F")
        w.node(np.array((p[0] * 1.42, p[1] * 1.42)), r"\footnotesize$+2$",
               "anchor=center")
    game_node(w, (0, 0), "pplant", "P")
    panel_title(w, 0, 1.95, "a", "the payoff motif")
    w.end_scope()

    # (b) even cycle: perfect alternation
    w.begin_scope("shift={(4.6,0)}")
    hexpts = [(math.cos(a), math.sin(a))
              for a in [math.pi / 2 + i * math.pi / 3 for i in range(6)]]
    for i in range(6):
        w.edge(np.array(hexpts[i]), np.array(hexpts[(i + 1) % 6]), "gedge")
    for i, p in enumerate(hexpts):
        game_node(w, p, "pplant" if i % 2 == 0 else "factory",
                  "P" if i % 2 == 0 else "F")
    panel_title(w, 0, 1.95, "b", "even cycle: perfect")
    w.end_scope()

    # (c) odd cycle: frustration
    w.begin_scope("shift={(9.2,0)}")
    pent = [(math.cos(a), math.sin(a))
            for a in [math.pi / 2 + i * 2 * math.pi / 5 for i in range(5)]]
    kinds = ["P", "F", "P", "F", "F"]
    for i in range(5):
        j = (i + 1) % 5
        style = "frustrated" if kinds[i] == kinds[j] else "gedge"
        w.edge(np.array(pent[i]), np.array(pent[j]), style)
    for p, k in zip(pent, kinds):
        game_node(w, p, "pplant" if k == "P" else "factory", k)
    mid = ((pent[3][0] + pent[4][0]) / 2, (pent[3][1] + pent[4][1]) / 2)
    w.node(np.array((mid[0] + 0.18, mid[1])),
           r"\footnotesize\textcolor{red!75!black}{frustrated}",
           "anchor=west")
    panel_title(w, 0, 1.95, "c", "odd cycle: frustrated")
    w.end_scope()

    w.line(tikzpicture_footer())
    out = HERE / f"{NAME}.tex"
    out.write_text(w.render())
    return out


if __name__ == "__main__":
    emit()
    build_pdf(NAME, HERE, cv_unit="1.05cm")
