#!/usr/bin/env python3
"""Rankings as altitude, cycles as the obstruction: the three-panel primer.

(a) a perfectly rankable 3-way tournament IS an altitude: every arrow's
    weight equals its altitude drop;
(b) the rock-paper-scissors triangle: a loop that "gains altitude" all the
    way around, which no assignment of heights can produce;
(c) a worked decomposition with numbers: an arbitrary tournament splits into
    altitude part + loop part.

Run: python3 writeup/figs/rank_primer/generate.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from _diagram_lib import (  # noqa: E402
    TikzWriter, fmt, tikzpicture_preamble, tikzpicture_footer, build_pdf,
)

NAME = HERE.name
R = "6pt"
NODE = "fill=black!12, draw=black, line width=0.5pt"


def labeled_node(w, p, name):
    w.filled_circle(np.array(p), R, NODE)
    w.node(np.array(p), rf"\small\textbf{{{name}}}", "anchor=center")


def flow_arrow(w, a, b, label, *, style="flow", pos="midway, above, sloped",
               shorten=0.24):
    a, b = np.array(a, float), np.array(b, float)
    d = (b - a) / np.linalg.norm(b - a)
    p, q = a + shorten * d, b - shorten * d
    w.line(f"    \\draw[{style}] ({fmt(p[0])},{fmt(p[1])}) -- "
           f"node[{pos}, font=\\footnotesize] {{{label}}} "
           f"({fmt(q[0])},{fmt(q[1])});")


def title(w, x, y, letter, text):
    w.node(np.array((x, y)), rf"\small\textbf{{({letter})}} {text}",
           "anchor=center")


def emit() -> Path:
    w = TikzWriter()
    w.line(tikzpicture_preamble(
        cv_unit="1.15cm",
        note=f"Auto-generated by writeup/figs/{NAME}/generate.py.",
    ))

    # (a) a rankable tournament is an altitude -------------------------
    w.begin_scope("shift={(0,0)}")
    A, B, C = (1.5, 2.6), (1.5, 1.3), (1.5, 0.0)
    # altitude axis
    w.line("    \\draw[-{Stealth[length=4pt]}, draw=black!45, "
           "line width=0.5pt] (-0.3,-0.3) -- (-0.3,3.0);")
    w.node(np.array((-0.3, 3.15)), r"\footnotesize altitude $s$",
           "anchor=south")
    for p, s in ((A, "+0.3"), (B, "0.0"), (C, "-0.3")):
        w.line(f"    \\draw[draw=black!25, line width=0.4pt, "
               f"dash pattern=on 1.5pt off 1.5pt] (-0.3,{p[1]}) -- "
               f"({p[0] - 0.28},{p[1]});")
        w.node(np.array((-0.42, p[1])),
               rf"\footnotesize ${s.replace('-', '-')}$", "anchor=east")
    flow_arrow(w, A, B, "0.3")
    flow_arrow(w, B, C, "0.3")
    w.line(f"    \\draw[flow] ({A[0] + 0.24},{A[1] - 0.1}) "
           f"to[bend left=40] node[midway, right, font=\\footnotesize] "
           f"{{0.6}} ({C[0] + 0.24},{C[1] + 0.1});")
    for p, nm in ((A, "A"), (B, "B"), (C, "C")):
        labeled_node(w, p, nm)
    title(w, 1.3, 3.7, "a", "rankable = an altitude")
    w.end_scope()

    # (b) the cycle that defeats every altitude ------------------------
    w.begin_scope("shift={(5.2,0.35)}")
    import math
    tri = [(1.1 + 1.15 * math.cos(a), 1.0 + 1.15 * math.sin(a))
           for a in (math.pi / 2, math.pi / 2 + 2 * math.pi / 3,
                     math.pi / 2 + 4 * math.pi / 3)]
    flow_arrow(w, tri[0], tri[1], "0.25")
    flow_arrow(w, tri[1], tri[2], "0.25")
    flow_arrow(w, tri[2], tri[0], "0.25")
    for p, nm in zip(tri, ("A", "B", "C")):
        labeled_node(w, p, nm)
    w.node(np.array((1.1, -0.62)),
           r"\footnotesize gain around the loop: $+0.75 \neq 0$",
           "anchor=center")
    title(w, 1.1, 3.35, "b", "a cycle defeats every altitude")
    w.end_scope()

    # (c) worked decomposition ------------------------------------------
    w.begin_scope("shift={(9.3,0.35)}")
    import math as m

    def mini(cx, wts, styles, label):
        tri = [(cx + 0.72 * m.cos(a), 1.15 + 0.72 * m.sin(a))
               for a in (m.pi / 2, m.pi / 2 + 2 * m.pi / 3,
                         m.pi / 2 + 4 * m.pi / 3)]
        pairs = [(0, 1), (1, 2), (0, 2)]
        for (i, j), wt, st in zip(pairs, wts, styles):
            if wt is None:
                w.edge(np.array(tri[i]), np.array(tri[j]),
                       "draw=black!30, line width=0.5pt")
            else:
                a_, b_ = (tri[i], tri[j]) if not wt.startswith("-") \
                    else (tri[j], tri[i])
                flow_arrow(w, a_, b_, wt.lstrip("-"), style=st, shorten=0.18,
                           pos="midway, above, sloped")
        for p, nm in zip(tri, ("A", "B", "C")):
            w.filled_circle(np.array(p), "4.5pt", NODE)
            w.node(np.array(p), rf"\scriptsize\textbf{{{nm}}}",
                   "anchor=center")
        w.node(np.array((cx, -0.15)), rf"\footnotesize {label}",
               "anchor=center")

    mini(0.0, ["0.4", "0.1", "0.2"], ["flow"] * 3, "tournament")
    w.node(np.array((1.55, 1.1)), r"\small$=$", "anchor=center")
    mini(3.1, ["0.3", None, "0.3"], ["flow", "", "flow"], "altitude part")
    w.node(np.array((4.65, 1.1)), r"\small$+$", "anchor=center")
    mini(6.2, ["0.1", "0.1", "-0.1"],
         ["consign"] * 3, "loop part")
    title(w, 3.1, 3.35, "c", "every tournament splits into the two")
    w.end_scope()

    w.line(tikzpicture_footer())
    out = HERE / f"{NAME}.tex"
    out.write_text(w.render())
    return out


if __name__ == "__main__":
    emit()
    build_pdf(NAME, HERE, cv_unit="1.15cm")
